version: '3.8'
services:
    laravel.test:
        build:
            context: .
            dockerfile: docker/8.4/Dockerfile
            args:
                WWWGROUP: '1000'
                WWWUSER: '1000'
        image: 'laravel-app'
        container_name: laravel.test
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
        ports:
            - '9000:9000'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_APP_KEY: '${APP_KEY}'
            DB_CONNECTION: 'mysql'
            DB_HOST: 'mysql'
            DB_PORT: '3306'
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        networks:
            - sail
        depends_on:
            - mysql

    nginx:
        image: 'nginx:alpine'
        container_name: nginx
        restart: unless-stopped
        ports:
            - '8000:80'
            - '443:443'
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - sail
        depends_on:
            - laravel.test

    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        ports:
            - '3307:3306'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local